### PR TITLE
filtered product types

### LINKED ISSUE #1: Amazon dataset cleaning and exploration
We are using the [Amazon dataset](https://nijianmo.github.io/amazon/index.html) for the recommender system to recommend Quinn users with beauty products. 

We would have to clean and select relevant features for our recommender systems. This will also be influenced by parameters provided by users in the survey.

### PR DESCRIPTION
**Pull request by ebonnecab**
I isolated the columns that actually describe what the product is and searched for the rows containing certain keywords. It's a little hacky but it works. Let me know what you think or how this code can be improved.

### CODE REVIEW

**Comment by xiwang129** [comment]
thank uuu Ebonne! I think we could add two more columns from the amazon review dataset. 1) reviewText 2) image. And one more from the metadata dataset: 1) price. Let's try to scrape some more men's skincare products later today. We might need to narrow it down further:)

**Review by xiwang129 — COMMENTED** [review]
thank uuu Ebonne! I think we could add two more columns from the amazon review dataset. 1) reviewText 2) image. And one more from the metadata dataset: 1) price. Let's try to scrape some more men's skincare products later today. We might need to narrow it down further:)

**Comment by ebonnecab** [comment]
> thank uuu Ebonne! I think we could add two more columns from the amazon review dataset. 1) reviewText 2) image. And one more from the metadata dataset: 1) price. Let's try to scrape some more men's skincare products later today. We might need to narrow it down further:)

this is just meant to be a way to get the indices of the relevant products for the real dataset. kinda like a filter to apply over it. the original dataset has all the needed metadata. I know its not 100% accurate and there are probably more keywords I can add. if you have any ideas on how to further narrow it down lmk

**Review by 0x1za — APPROVED** [review]
LGTM 🚀

**Pull request merged**
